spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          prepare_sql: false
jwt:
  secret: ${JWT_SECRET}
github:
  client:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
  api:
    base-url: https://api.github.com
webhook:
  callback-url: ${WEBHOOK_CALLBACK_URL}
  secret: ${WEBHOOK_SECRET}
springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH}