spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 0
      initialization-fail-timeout: 0
      idle-timeout: 30000 # 30초
      max-lifetime: 170000 # 2분 50초
      connection-timeout: 10000 # 10초
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          prepare_sql: false
  # Gemini API
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.8
        embedding:
          project-id: ${GEMINI_PROJECT_ID}
          location: us-central1

jwt:
  secret: ${JWT_SECRET}

github:
  client:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
  api:
    base-url: https://api.github.com

webhook:
  callback-url: ${WEBHOOK_CALLBACK_URL}
  secret: ${WEBHOOK_SECRET}

springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH}